export type ContextEventKind = "input" | "assistant" | "tool_call" | "tool_result" | "provider" | "lifecycle" | "summary";
export type ContextEvent = {
    id: string;
    runId: string;
    parentRunId?: string;
    ts: string;
    cwd: string;
    agent: string;
    kind: ContextEventKind;
    eventName: string;
    text?: string;
    toolName?: string;
    bytes: number;
    estimatedTokens: number;
    sourceIds?: string[];
    payload?: unknown;
};
export type MemoryItem = {
    id: string;
    runId: string;
    ts: string;
    cwd: string;
    scope: "agent" | "project";
    category: "summary" | "decision" | "preference" | "fact" | "error" | "file" | "command" | "open_question" | "next_action" | "project_context" | "task_context" | "working_rule" | "routing_rule" | "skill_rule" | "retrieval_pointer";
    text: string;
    importance: number;
    confidence: number;
    sourceIds: string[];
    promoted?: boolean;
};
export type ContextPaths = {
    root: string;
    runsDir: string;
    memoryDir: string;
    projectMemoryPath: string;
};
export declare function defaultRoot(): string;
export declare function contextPaths(root?: string): ContextPaths;
export declare function ensureStore(root?: string): ContextPaths;
export declare function safeIdPart(value: string): string;
export declare function newId(prefix: string): string;
export declare function estimateTokensFromText(text: string): number;
export declare function runEventsPath(runId: string, root?: string): string;
export declare function runMemoryPath(runId: string, root?: string): string;
export declare function appendJsonl(path: string, row: unknown): void;
export declare function appendContextEvent(event: ContextEvent, root?: string): void;
export declare function appendMemoryItems(runId: string, items: MemoryItem[], root?: string): void;
export declare function appendProjectMemory(items: MemoryItem[], root?: string): void;
export declare function readJsonl<T>(path: string): T[];
export declare function readRunEvents(runId: string, root?: string): ContextEvent[];
export declare function readRunMemory(runId: string, root?: string): MemoryItem[];
export declare function latestRunIds(limit?: number, root?: string): string[];
export declare function storeStats(root?: string): {
    runs: number;
    memories: number;
    projectMemories: number;
    eventBytes: number;
    memoryBytes: number;
    root: string;
};
export declare function writeSnapshot(path: string, value: unknown): void;
